# Generated by Django 4.2 on 2024-09-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0002_chatgroup_created_at_chatgroup_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatgroup",
            old_name="group_name",
            new_name="name",
        ),
    ]
