version: "3.9"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  db:
      image: postgres:latest
      container_name: POSTGRES_DB
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./data/db:/var/lib/postgresql/data/

  backend:
      build: .
      container_name: backend
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./core:/app
      ports:
        - "8000:8000"
      depends_on:
        - redis
        - db
    
  
  worker:
      build: .
      command: celery -A Core worker --loglevel=info
      volumes:
        - ./core:/app
      depends_on:
        - redis
        - backend
